import type { Trip } from '../types'
import { DEFAULT_PACKING_CATEGORIES } from './validate'

function id(prefix: string, n: number | string) {
  return `demo-${prefix}-${n}`
}

export function buildDemoTrip(): Trip {
  return {
    id: 'demo-europa-2024',
    name: 'Europa 2024',
    startDate: '2024-05-20',
    endDate: '2024-06-24',
    travelers: [
      { id: id('t', 1), name: 'Peeter' },
      { id: id('t', 2), name: 'Cacho' },
      { id: id('t', 3), name: 'Rama' },
      { id: id('t', 4), name: 'Nacho' },
    ],

    transports: [
      {
        id: id('tr', 1), type: 'avión',
        origin: 'Buenos Aires', destination: 'Barcelona',
        departureDate: '2024-05-20', departureTime: '12:00',
        arrivalDate: '2024-05-21', arrivalTime: '05:30',
        bookingCode: '', company: 'Iberia', notes: 'Escala en Madrid',
      },
      {
        id: id('tr', 2), type: 'tren',
        origin: 'Barcelona', destination: 'Madrid',
        departureDate: '2024-05-25', departureTime: '11:55',
        arrivalDate: '2024-05-25', arrivalTime: '14:40',
        bookingCode: 'WZSLUN', company: 'Iryo', notes: '',
      },
      {
        id: id('tr', 3), type: 'avión',
        origin: 'Madrid', destination: 'Paris',
        departureDate: '2024-05-27', departureTime: '13:05',
        arrivalDate: '2024-05-27', arrivalTime: '15:10',
        bookingCode: 'X5D68B', company: 'Transavia', notes: '',
      },
      {
        id: id('tr', 4), type: 'avión',
        origin: 'Paris', destination: 'Londres',
        departureDate: '2024-05-31', departureTime: '13:00',
        arrivalDate: '2024-05-31', arrivalTime: '13:10',
        bookingCode: 'QJ3K8T', company: 'Vueling', notes: '',
      },
      {
        id: id('tr', 5), type: 'avión',
        origin: 'Londres', destination: 'Edimburgo',
        departureDate: '2024-06-04', departureTime: '18:15',
        arrivalDate: '2024-06-04', arrivalTime: '19:40',
        bookingCode: 'N3N5UZ', company: 'British Airways', notes: '',
      },
      {
        id: id('tr', 6), type: 'avión',
        origin: 'Edimburgo', destination: 'Amsterdam',
        departureDate: '2024-06-07', departureTime: '20:35',
        arrivalDate: '2024-06-07', arrivalTime: '22:55',
        bookingCode: 'HC55GW', company: 'Transavia', notes: '',
      },
      {
        id: id('tr', 7), type: 'bus',
        origin: 'Amsterdam', destination: 'Bruselas',
        departureDate: '2024-06-11', departureTime: '08:35',
        arrivalDate: '2024-06-11', arrivalTime: '11:50',
        bookingCode: '316 034 1330', company: 'Flixbus', notes: '',
      },
      {
        id: id('tr', 8), type: 'avión',
        origin: 'Bruselas', destination: 'Praga',
        departureDate: '2024-06-13', departureTime: '13:10',
        arrivalDate: '2024-06-13', arrivalTime: '14:40',
        bookingCode: 'WUC7TE', company: 'Ryanair', notes: '',
      },
      {
        id: id('tr', 9), type: 'avión',
        origin: 'Praga', destination: 'Pisa',
        departureDate: '2024-06-16', departureTime: '12:30',
        arrivalDate: '2024-06-16', arrivalTime: '14:10',
        bookingCode: 'CLE8SZ', company: 'Ryanair', notes: '',
      },
      {
        id: id('tr', 10), type: 'avión',
        origin: 'Roma', destination: 'Barcelona',
        departureDate: '2024-06-21', departureTime: '20:35',
        arrivalDate: '2024-06-21', arrivalTime: '22:20',
        bookingCode: 'DHJCNV', company: 'Ryanair', notes: '',
      },
      {
        id: id('tr', 11), type: 'avión',
        origin: 'Barcelona', destination: 'Buenos Aires',
        departureDate: '2024-06-24', departureTime: '21:05',
        arrivalDate: '2024-06-25', arrivalTime: '08:00',
        bookingCode: '', company: 'Iberia', notes: 'Escala en Madrid',
      },
    ],

    accommodations: [
      {
        id: id('a', 1), city: 'Barcelona', nights: 4,
        confirmationCode: '', pin: '', phone: '',
        address: '', notes: 'Casa de Peter',
      },
      {
        id: id('a', 2), city: 'Madrid', nights: 2,
        confirmationCode: '4682562659', pin: '8626', phone: '+34 601 50 52 25',
        address: 'Cuesta de Santo Domingo 24, 1ra planta, Centro, Madrid 28013',
        notes: 'PIN confidencial',
      },
      {
        id: id('a', 3), city: 'Paris', nights: 4,
        confirmationCode: 'HMJQ3RSX3X', pin: '', phone: '+33 7 58 644228',
        address: '22 Rue du Pont Louis-Philippe, París 75004',
        notes: '',
      },
      {
        id: id('a', 4), city: 'Londres', nights: 4,
        confirmationCode: '', pin: '', phone: '',
        address: 'Dirección a confirmar',
        notes: '',
      },
      {
        id: id('a', 5), city: 'Edimburgo', nights: 3,
        confirmationCode: '4420961950', pin: '9977', phone: '+44 131 221 1331',
        address: '34 Gilmore Place, Edimburgo EH3 9NQ',
        notes: '',
      },
      {
        id: id('a', 6), city: 'Amsterdam', nights: 3,
        confirmationCode: '', pin: '', phone: '',
        address: 'Dirección a confirmar',
        notes: 'Casa de Ro y Lucho',
      },
      {
        id: id('a', 7), city: 'Bruselas', nights: 2,
        confirmationCode: '4899876305', pin: '5427', phone: '+61 478 659 744',
        address: '67 Rue de Stassart, Ixelles 1050 Bruselas',
        notes: '',
      },
      {
        id: id('a', 8), city: 'Praga', nights: 3,
        confirmationCode: 'HMNN854DXK', pin: '', phone: '+420 773 183 777',
        address: 'V Tůních 1768/14, Praha 2, 120 00',
        notes: 'Behsud restaurant',
      },
      {
        id: id('a', 9), city: 'Florencia', nights: 3,
        confirmationCode: '', pin: '', phone: '',
        address: '', notes: '',
      },
      {
        id: id('a', 10), city: 'Roma', nights: 3,
        confirmationCode: 'HMX23D2ZQE', pin: '', phone: '',
        address: 'Dirección a confirmar',
        notes: '',
      },
    ],

    itinerary: [
      { date: '2024-05-20', city: 'Buenos Aires', notes: '12:00 Salida a Barcelona' },
      { date: '2024-05-21', city: 'Barcelona', notes: '05:30 Llegada' },
      { date: '2024-05-22', city: 'Barcelona', notes: '' },
      { date: '2024-05-23', city: 'Barcelona', notes: '' },
      { date: '2024-05-24', city: 'Barcelona', notes: '' },
      { date: '2024-05-25', city: 'Madrid', notes: 'Tren desde Barcelona 11:55' },
      { date: '2024-05-26', city: 'Madrid', notes: '' },
      { date: '2024-05-27', city: 'Paris', notes: 'Vuelo desde Madrid 13:05' },
      { date: '2024-05-28', city: 'Paris', notes: '' },
      { date: '2024-05-29', city: 'Paris', notes: '' },
      { date: '2024-05-30', city: 'Paris', notes: '' },
      { date: '2024-05-31', city: 'Londres', notes: 'Vuelo desde Paris 13:00' },
      { date: '2024-06-01', city: 'Londres', notes: 'Wembley — Final de Champions' },
      { date: '2024-06-02', city: 'Londres', notes: '' },
      { date: '2024-06-03', city: 'Londres', notes: '' },
      { date: '2024-06-04', city: 'Edimburgo', notes: 'Vuelo desde Londres 18:15' },
      { date: '2024-06-05', city: 'Edimburgo', notes: '' },
      { date: '2024-06-06', city: 'Edimburgo', notes: '' },
      { date: '2024-06-07', city: 'Amsterdam', notes: 'Vuelo desde Edimburgo 20:35' },
      { date: '2024-06-08', city: 'Amsterdam', notes: '' },
      { date: '2024-06-09', city: 'Amsterdam', notes: '' },
      { date: '2024-06-10', city: 'Amsterdam', notes: '' },
      { date: '2024-06-11', city: 'Bruselas', notes: 'Bus desde Amsterdam 08:35' },
      { date: '2024-06-12', city: 'Bruselas', notes: 'Excursión Brujas / Gante' },
      { date: '2024-06-13', city: 'Praga', notes: 'Vuelo desde Bruselas 13:10' },
      { date: '2024-06-14', city: 'Praga', notes: '' },
      { date: '2024-06-15', city: 'Praga', notes: '' },
      { date: '2024-06-16', city: 'Florencia', notes: 'Vuelo a Pisa 12:30, tren/auto a Florencia' },
      { date: '2024-06-17', city: 'Florencia', notes: '' },
      { date: '2024-06-18', city: 'Roma', notes: 'Viaje desde Florencia' },
      { date: '2024-06-19', city: 'Roma', notes: '' },
      { date: '2024-06-20', city: 'Roma', notes: '' },
      { date: '2024-06-21', city: 'Barcelona', notes: 'Vuelo desde Roma 20:35' },
      { date: '2024-06-22', city: 'Barcelona', notes: '' },
      { date: '2024-06-23', city: 'Barcelona', notes: '' },
      { date: '2024-06-24', city: 'Buenos Aires', notes: '21:05 Vuelta a casa' },
    ],

    activities: [
      { id: id('ac', 1), date: '2024-06-01', city: 'Londres', place: 'Wembley Stadium', type: 'Show/Evento', notes: 'Final de Champions League' },
      { id: id('ac', 2), date: '2024-06-12', city: 'Bruselas', place: 'Brujas', type: 'Excursión', notes: 'Day trip desde Bruselas' },
      { id: id('ac', 3), date: '2024-06-12', city: 'Bruselas', place: 'Gante', type: 'Excursión', notes: 'Combinado con Brujas' },
    ],

    expenses: [
      { id: id('e', 1), concept: 'Alojamiento Londres', date: '', detail: '', price: 550, paid: 550, reserved: true, currency: 'USD' },
      { id: id('e', 2), concept: 'Alojamiento Edimburgo', date: '', detail: '', price: 607, paid: 607, reserved: true, currency: 'USD' },
      { id: id('e', 3), concept: 'Alojamiento Bruselas', date: '', detail: '', price: 273, paid: 273, reserved: true, currency: 'USD' },
      { id: id('e', 4), concept: 'Alojamiento Praga', date: '', detail: '', price: 380, paid: 352, reserved: true, currency: 'USD' },
      { id: id('e', 5), concept: 'Alojamiento Madrid', date: '', detail: '', price: 218, paid: 218, reserved: true, currency: 'USD' },
      { id: id('e', 6), concept: 'Alojamiento París', date: '', detail: '', price: 555, paid: 555, reserved: true, currency: 'USD' },
      { id: id('e', 7), concept: 'Alojamiento Roma', date: '', detail: '', price: 486, paid: 467, reserved: true, currency: 'USD' },
      { id: id('e', 8), concept: 'Alojamiento Florencia', date: '', detail: '', price: 279, paid: 279, reserved: true, currency: 'USD' },
      { id: id('e', 9), concept: 'Vuelo a Pisa', date: '2024-06-16', detail: 'Praga → Pisa', price: 203, paid: 203, reserved: true, currency: 'USD' },
      { id: id('e', 10), concept: 'Tren a Madrid', date: '2024-05-25', detail: 'Barcelona → Madrid (Iryo)', price: 111, paid: 111, reserved: true, currency: 'USD' },
      { id: id('e', 11), concept: 'Vuelo a Barcelona', date: '2024-06-21', detail: 'Roma → Barcelona', price: 169, paid: 169, reserved: true, currency: 'USD' },
      { id: id('e', 12), concept: 'Vuelo a Paris', date: '2024-05-27', detail: 'Madrid → Paris', price: 310, paid: 310, reserved: true, currency: 'USD' },
      { id: id('e', 13), concept: 'Vuelo a Rotterdam', date: '', detail: 'Escala Amsterdam', price: 220, paid: 220, reserved: true, currency: 'USD' },
      { id: id('e', 14), concept: 'Vuelo a Praga', date: '2024-06-13', detail: 'Bruselas → Praga', price: 150, paid: 150, reserved: true, currency: 'USD' },
      { id: id('e', 15), concept: 'Bus a Bruselas', date: '2024-06-11', detail: 'Amsterdam → Bruselas (Flixbus)', price: 28, paid: 28, reserved: true, currency: 'USD' },
      { id: id('e', 16), concept: 'Vuelo a Londres', date: '2024-05-31', detail: 'Paris → Londres', price: 460, paid: 460, reserved: true, currency: 'USD' },
      { id: id('e', 17), concept: 'Vuelo a Edimburgo', date: '2024-06-04', detail: 'Londres → Edimburgo', price: 200, paid: 200, reserved: true, currency: 'USD' },
    ],

    expenseSplits: [
      { id: id('s', 1), concept: 'Alojamiento Londres', paidBy: 'Rama', currency: 'USD', amount: 550 },
      { id: id('s', 2), concept: 'Alojamiento Edimburgo', paidBy: 'Rama', currency: 'USD', amount: 607 },
      { id: id('s', 3), concept: 'Alojamiento París', paidBy: 'Rama', currency: 'USD', amount: 555 },
      { id: id('s', 4), concept: 'Alojamiento Bruselas', paidBy: 'Cacho', currency: 'USD', amount: 273 },
      { id: id('s', 5), concept: 'Alojamiento Praga', paidBy: 'Cacho', currency: 'USD', amount: 380 },
      { id: id('s', 6), concept: 'Alojamiento Roma', paidBy: 'Cacho', currency: 'USD', amount: 486 },
      { id: id('s', 7), concept: 'Alojamiento Florencia', paidBy: 'Cacho', currency: 'USD', amount: 279 },
      { id: id('s', 8), concept: 'Bus a Bruselas', paidBy: 'Cacho', currency: 'USD', amount: 28 },
      { id: id('s', 9), concept: 'Vuelo a Londres', paidBy: 'Cacho', currency: 'USD', amount: 460 },
      { id: id('s', 10), concept: 'Vuelo a Edimburgo', paidBy: 'Cacho', currency: 'USD', amount: 200 },
      { id: id('s', 11), concept: 'Alojamiento Madrid', paidBy: 'Peeter', currency: 'USD', amount: 218 },
      { id: id('s', 12), concept: 'Vuelo a Pisa', paidBy: 'Peeter', currency: 'USD', amount: 203 },
      { id: id('s', 13), concept: 'Tren a Madrid', paidBy: 'Peeter', currency: 'USD', amount: 111 },
      { id: id('s', 14), concept: 'Vuelo a Barcelona', paidBy: 'Peeter', currency: 'USD', amount: 169 },
      { id: id('s', 15), concept: 'Vuelo a Paris', paidBy: 'Peeter', currency: 'USD', amount: 310 },
      { id: id('s', 16), concept: 'Vuelo a Rotterdam', paidBy: 'Peeter', currency: 'USD', amount: 220 },
      { id: id('s', 17), concept: 'Vuelo a Praga', paidBy: 'Peeter', currency: 'USD', amount: 150 },
    ],

    packingList: DEFAULT_PACKING_CATEGORIES(),
  }
}
