import type { Trip } from '../types'
import { DEFAULT_PACKING_CATEGORIES } from './validate'

function id(prefix: string, n: number | string) {
  return `demo-${prefix}-${n}`
}

export function buildDemoTrip(): Trip {
  return {
    id: 'demo-europa-2024',
    name: 'Europa 2024',
    startDate: '2024-05-20',
    endDate: '2024-06-24',
    travelers: [
      { id: id('t', 1), name: 'Ana' },
      { id: id('t', 2), name: 'Bruno' },
      { id: id('t', 3), name: 'Clara' },
      { id: id('t', 4), name: 'Diego' },
    ],

    transports: [
      {
        id: id('tr', 1), type: 'avión', url: '',
        origin: 'Buenos Aires', destination: 'Barcelona',
        departureDate: '2024-05-20', departureTime: '12:00',
        arrivalDate: '2024-05-21', arrivalTime: '05:30',
        bookingCode: '', company: 'Iberia', notes: 'Escala en Madrid',
      },
      {
        id: id('tr', 2), type: 'tren', url: '',
        origin: 'Barcelona', destination: 'Madrid',
        departureDate: '2024-05-25', departureTime: '11:55',
        arrivalDate: '2024-05-25', arrivalTime: '14:40',
        bookingCode: 'ABCDE1', company: 'Iryo', notes: '',
      },
      {
        id: id('tr', 3), type: 'avión', url: '',
        origin: 'Madrid', destination: 'Paris',
        departureDate: '2024-05-27', departureTime: '13:05',
        arrivalDate: '2024-05-27', arrivalTime: '15:10',
        bookingCode: 'ABCDE2', company: 'Transavia', notes: '',
      },
      {
        id: id('tr', 4), type: 'avión', url: '',
        origin: 'Paris', destination: 'Londres',
        departureDate: '2024-05-31', departureTime: '13:00',
        arrivalDate: '2024-05-31', arrivalTime: '13:10',
        bookingCode: 'ABCDE3', company: 'Vueling', notes: '',
      },
      {
        id: id('tr', 5), type: 'avión', url: '',
        origin: 'Londres', destination: 'Edimburgo',
        departureDate: '2024-06-04', departureTime: '18:15',
        arrivalDate: '2024-06-04', arrivalTime: '19:40',
        bookingCode: 'ABCDE4', company: 'British Airways', notes: '',
      },
      {
        id: id('tr', 6), type: 'avión', url: '',
        origin: 'Edimburgo', destination: 'Amsterdam',
        departureDate: '2024-06-07', departureTime: '20:35',
        arrivalDate: '2024-06-07', arrivalTime: '22:55',
        bookingCode: 'ABCDE5', company: 'Transavia', notes: '',
      },
      {
        id: id('tr', 7), type: 'bus', url: '',
        origin: 'Amsterdam', destination: 'Bruselas',
        departureDate: '2024-06-11', departureTime: '08:35',
        arrivalDate: '2024-06-11', arrivalTime: '11:50',
        bookingCode: 'ABCDE6', company: 'Flixbus', notes: '',
      },
      {
        id: id('tr', 8), type: 'avión', url: '',
        origin: 'Bruselas', destination: 'Praga',
        departureDate: '2024-06-13', departureTime: '13:10',
        arrivalDate: '2024-06-13', arrivalTime: '14:40',
        bookingCode: 'ABCDE7', company: 'Ryanair', notes: '',
      },
      {
        id: id('tr', 9), type: 'avión', url: '',
        origin: 'Praga', destination: 'Pisa',
        departureDate: '2024-06-16', departureTime: '12:30',
        arrivalDate: '2024-06-16', arrivalTime: '14:10',
        bookingCode: 'ABCDE8', company: 'Ryanair', notes: '',
      },
      {
        id: id('tr', 10), type: 'avión', url: '',
        origin: 'Roma', destination: 'Barcelona',
        departureDate: '2024-06-21', departureTime: '20:35',
        arrivalDate: '2024-06-21', arrivalTime: '22:20',
        bookingCode: 'ABCDE9', company: 'Ryanair', notes: '',
      },
      {
        id: id('tr', 11), type: 'avión', url: '',
        origin: 'Barcelona', destination: 'Buenos Aires',
        departureDate: '2024-06-24', departureTime: '21:05',
        arrivalDate: '2024-06-25', arrivalTime: '08:00',
        bookingCode: '', company: 'Iberia', notes: 'Escala en Madrid',
      },
    ],

    accommodations: [
      {
        id: id('a', 1), city: 'Barcelona', nights: 4,
        confirmationCode: '', pin: '', phone: '',
        address: 'Calle Ejemplo 10, Barcelona 08001', notes: '', url: '',
      },
      {
        id: id('a', 2), city: 'Madrid', nights: 2,
        confirmationCode: 'DEMO1234567', pin: '0000', phone: '+34 600 000 001',
        address: 'Calle Gran Vía 1, Centro, Madrid 28013',
        notes: '', url: '',
      },
      {
        id: id('a', 3), city: 'Paris', nights: 4,
        confirmationCode: 'DEMO2345678', pin: '', phone: '+33 6 00 00 00 01',
        address: '10 Rue de Rivoli, París 75001',
        notes: '', url: '',
      },
      {
        id: id('a', 4), city: 'Londres', nights: 4,
        confirmationCode: '', pin: '', phone: '',
        address: 'Dirección a confirmar',
        notes: '', url: '',
      },
      {
        id: id('a', 5), city: 'Edimburgo', nights: 3,
        confirmationCode: 'DEMO3456789', pin: '1234', phone: '+44 131 000 0001',
        address: '10 Royal Mile, Edimburgo EH1 1TH',
        notes: '', url: '',
      },
      {
        id: id('a', 6), city: 'Amsterdam', nights: 3,
        confirmationCode: '', pin: '', phone: '',
        address: 'Dirección a confirmar',
        notes: '', url: '',
      },
      {
        id: id('a', 7), city: 'Bruselas', nights: 2,
        confirmationCode: 'DEMO4567890', pin: '5678', phone: '+32 2 000 0001',
        address: 'Rue du Marché 5, Ixelles 1050 Bruselas',
        notes: '', url: '',
      },
      {
        id: id('a', 8), city: 'Praga', nights: 3,
        confirmationCode: 'DEMO5678901', pin: '', phone: '+420 700 000 001',
        address: 'Náměstí Míru 1, Praha 2, 120 00',
        notes: '', url: '',
      },
      {
        id: id('a', 9), city: 'Florencia', nights: 3,
        confirmationCode: '', pin: '', phone: '',
        address: '', notes: '', url: '',
      },
      {
        id: id('a', 10), city: 'Roma', nights: 3,
        confirmationCode: 'DEMO6789012', pin: '', phone: '',
        address: 'Dirección a confirmar',
        notes: '', url: '',
      },
    ],

    itinerary: [
      { date: '2024-05-20', city: 'Buenos Aires', notes: '12:00 Salida a Barcelona' },
      { date: '2024-05-21', city: 'Barcelona', notes: '05:30 Llegada' },
      { date: '2024-05-22', city: 'Barcelona', notes: '' },
      { date: '2024-05-23', city: 'Barcelona', notes: '' },
      { date: '2024-05-24', city: 'Barcelona', notes: '' },
      { date: '2024-05-25', city: 'Madrid', notes: 'Tren desde Barcelona 11:55' },
      { date: '2024-05-26', city: 'Madrid', notes: '' },
      { date: '2024-05-27', city: 'Paris', notes: 'Vuelo desde Madrid 13:05' },
      { date: '2024-05-28', city: 'Paris', notes: '' },
      { date: '2024-05-29', city: 'Paris', notes: '' },
      { date: '2024-05-30', city: 'Paris', notes: '' },
      { date: '2024-05-31', city: 'Londres', notes: 'Vuelo desde Paris 13:00' },
      { date: '2024-06-01', city: 'Londres', notes: 'Wembley — Final de Champions' },
      { date: '2024-06-02', city: 'Londres', notes: '' },
      { date: '2024-06-03', city: 'Londres', notes: '' },
      { date: '2024-06-04', city: 'Edimburgo', notes: 'Vuelo desde Londres 18:15' },
      { date: '2024-06-05', city: 'Edimburgo', notes: '' },
      { date: '2024-06-06', city: 'Edimburgo', notes: '' },
      { date: '2024-06-07', city: 'Amsterdam', notes: 'Vuelo desde Edimburgo 20:35' },
      { date: '2024-06-08', city: 'Amsterdam', notes: '' },
      { date: '2024-06-09', city: 'Amsterdam', notes: '' },
      { date: '2024-06-10', city: 'Amsterdam', notes: '' },
      { date: '2024-06-11', city: 'Bruselas', notes: 'Bus desde Amsterdam 08:35' },
      { date: '2024-06-12', city: 'Bruselas', notes: 'Excursión Brujas / Gante' },
      { date: '2024-06-13', city: 'Praga', notes: 'Vuelo desde Bruselas 13:10' },
      { date: '2024-06-14', city: 'Praga', notes: '' },
      { date: '2024-06-15', city: 'Praga', notes: '' },
      { date: '2024-06-16', city: 'Florencia', notes: 'Vuelo a Pisa 12:30, tren/auto a Florencia' },
      { date: '2024-06-17', city: 'Florencia', notes: '' },
      { date: '2024-06-18', city: 'Roma', notes: 'Viaje desde Florencia' },
      { date: '2024-06-19', city: 'Roma', notes: '' },
      { date: '2024-06-20', city: 'Roma', notes: '' },
      { date: '2024-06-21', city: 'Barcelona', notes: 'Vuelo desde Roma 20:35' },
      { date: '2024-06-22', city: 'Barcelona', notes: '' },
      { date: '2024-06-23', city: 'Barcelona', notes: '' },
      { date: '2024-06-24', city: 'Buenos Aires', notes: '21:05 Vuelta a casa' },
    ],

    activities: [
      { id: id('ac', 1), date: '2024-06-01', city: 'Londres', place: 'Wembley Stadium', type: 'Show/Evento', notes: 'Final de Champions League' },
      { id: id('ac', 2), date: '2024-06-12', city: 'Bruselas', place: 'Brujas', type: 'Excursión', notes: 'Day trip desde Bruselas' },
      { id: id('ac', 3), date: '2024-06-12', city: 'Bruselas', place: 'Gante', type: 'Excursión', notes: 'Combinado con Brujas' },
    ],

    expenses: [
      { id: id('e', 1), concept: 'Alojamiento Londres', date: '', detail: '', price: 500, paid: 500, reserved: true, currency: 'USD' },
      { id: id('e', 2), concept: 'Alojamiento Edimburgo', date: '', detail: '', price: 600, paid: 600, reserved: true, currency: 'USD' },
      { id: id('e', 3), concept: 'Alojamiento Bruselas', date: '', detail: '', price: 280, paid: 280, reserved: true, currency: 'USD' },
      { id: id('e', 4), concept: 'Alojamiento Praga', date: '', detail: '', price: 360, paid: 360, reserved: true, currency: 'USD' },
      { id: id('e', 5), concept: 'Alojamiento Madrid', date: '', detail: '', price: 220, paid: 220, reserved: true, currency: 'USD' },
      { id: id('e', 6), concept: 'Alojamiento París', date: '', detail: '', price: 560, paid: 560, reserved: true, currency: 'USD' },
      { id: id('e', 7), concept: 'Alojamiento Roma', date: '', detail: '', price: 480, paid: 480, reserved: true, currency: 'USD' },
      { id: id('e', 8), concept: 'Alojamiento Florencia', date: '', detail: '', price: 280, paid: 280, reserved: true, currency: 'USD' },
      { id: id('e', 9), concept: 'Vuelo a Pisa', date: '2024-06-16', detail: 'Praga → Pisa', price: 200, paid: 200, reserved: true, currency: 'USD' },
      { id: id('e', 10), concept: 'Tren a Madrid', date: '2024-05-25', detail: 'Barcelona → Madrid', price: 110, paid: 110, reserved: true, currency: 'USD' },
      { id: id('e', 11), concept: 'Vuelo a Barcelona', date: '2024-06-21', detail: 'Roma → Barcelona', price: 170, paid: 170, reserved: true, currency: 'USD' },
      { id: id('e', 12), concept: 'Vuelo a Paris', date: '2024-05-27', detail: 'Madrid → Paris', price: 300, paid: 300, reserved: true, currency: 'USD' },
      { id: id('e', 13), concept: 'Vuelo a Amsterdam', date: '', detail: 'Edimburgo → Amsterdam', price: 220, paid: 220, reserved: true, currency: 'USD' },
      { id: id('e', 14), concept: 'Vuelo a Praga', date: '2024-06-13', detail: 'Bruselas → Praga', price: 150, paid: 150, reserved: true, currency: 'USD' },
      { id: id('e', 15), concept: 'Bus a Bruselas', date: '2024-06-11', detail: 'Amsterdam → Bruselas (Flixbus)', price: 30, paid: 30, reserved: true, currency: 'USD' },
      { id: id('e', 16), concept: 'Vuelo a Londres', date: '2024-05-31', detail: 'Paris → Londres', price: 460, paid: 460, reserved: true, currency: 'USD' },
      { id: id('e', 17), concept: 'Vuelo a Edimburgo', date: '2024-06-04', detail: 'Londres → Edimburgo', price: 200, paid: 200, reserved: true, currency: 'USD' },
    ],

    expenseSplits: [
      { id: id('s', 1), concept: 'Alojamiento Londres', paidBy: 'Clara', currency: 'USD', amount: 500 },
      { id: id('s', 2), concept: 'Alojamiento Edimburgo', paidBy: 'Clara', currency: 'USD', amount: 600 },
      { id: id('s', 3), concept: 'Alojamiento París', paidBy: 'Clara', currency: 'USD', amount: 560 },
      { id: id('s', 4), concept: 'Alojamiento Bruselas', paidBy: 'Bruno', currency: 'USD', amount: 280 },
      { id: id('s', 5), concept: 'Alojamiento Praga', paidBy: 'Bruno', currency: 'USD', amount: 360 },
      { id: id('s', 6), concept: 'Alojamiento Roma', paidBy: 'Bruno', currency: 'USD', amount: 480 },
      { id: id('s', 7), concept: 'Alojamiento Florencia', paidBy: 'Bruno', currency: 'USD', amount: 280 },
      { id: id('s', 8), concept: 'Bus a Bruselas', paidBy: 'Bruno', currency: 'USD', amount: 30 },
      { id: id('s', 9), concept: 'Vuelo a Londres', paidBy: 'Bruno', currency: 'USD', amount: 460 },
      { id: id('s', 10), concept: 'Vuelo a Edimburgo', paidBy: 'Bruno', currency: 'USD', amount: 200 },
      { id: id('s', 11), concept: 'Alojamiento Madrid', paidBy: 'Ana', currency: 'USD', amount: 220 },
      { id: id('s', 12), concept: 'Vuelo a Pisa', paidBy: 'Ana', currency: 'USD', amount: 200 },
      { id: id('s', 13), concept: 'Tren a Madrid', paidBy: 'Ana', currency: 'USD', amount: 110 },
      { id: id('s', 14), concept: 'Vuelo a Barcelona', paidBy: 'Ana', currency: 'USD', amount: 170 },
      { id: id('s', 15), concept: 'Vuelo a Paris', paidBy: 'Ana', currency: 'USD', amount: 300 },
      { id: id('s', 16), concept: 'Vuelo a Amsterdam', paidBy: 'Ana', currency: 'USD', amount: 220 },
      { id: id('s', 17), concept: 'Vuelo a Praga', paidBy: 'Ana', currency: 'USD', amount: 150 },
    ],

    packingList: DEFAULT_PACKING_CATEGORIES(),
    notes: '',
    auditLog: [],
  }
}
